'use strict';

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up (queryInterface, Sequelize) {
    /**
     * Add seed commands here.
     *
     * Example:
     * await queryInterface.bulkInsert('People', [{
     *   name: 'John Doe',
     *   isBetaMember: false
     * }], {});
    */
    await queryInterface.bulkInsert('safety', [
      {
        version_id: 1,
        so_tui_khi: 6,
        ABS: 'yes',
        EBD: 'yes',
        EBA: 'yes',
        ESS: 'yes',
        DSC: 'yes',
        TCS: 'yes',
        HLA: 'yes',
        ma_hoa_chong_sao_chep_chia_khoa: 'yes',
        canh_bao_chong_trom: 'yes',
        camera_lui: 'yes',
        cam_bien_canh_bao_va_cham_phia_sau: 'yes',
        cam_bien_canh_bao_va_cham_phia_truoc: 'yes',
        camera_quan_sat_360: 'no',
        canh_bao_that_day_an_toan: 'no',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        version_id: 1,
        so_tui_khi: 6,
        ABS: 'yes',
        EBD: 'yes',
        EBA: 'yes',
        ESS: 'yes',
        DSC: 'yes',
        TCS: 'yes',
        HLA: 'yes',
        ma_hoa_chong_sao_chep_chia_khoa: 'yes',
        canh_bao_chong_trom: 'yes',
        camera_lui: 'yes',
        cam_bien_canh_bao_va_cham_phia_sau: 'yes',
        cam_bien_canh_bao_va_cham_phia_truoc: 'yes',
        camera_quan_sat_360: 'no',
        canh_bao_that_day_an_toan: 'no',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        version_id: 1,
        so_tui_khi: 6,
        ABS: 'yes',
        EBD: 'yes',
        EBA: 'yes',
        ESS: 'yes',
        DSC: 'yes',
        TCS: 'yes',
        HLA: 'yes',
        ma_hoa_chong_sao_chep_chia_khoa: 'yes',
        canh_bao_chong_trom: 'yes',
        camera_lui: 'yes',
        cam_bien_canh_bao_va_cham_phia_sau: 'yes',
        cam_bien_canh_bao_va_cham_phia_truoc: 'yes',
        camera_quan_sat_360: 'no',
        canh_bao_that_day_an_toan: 'no',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        version_id: 1,
        so_tui_khi: 6,
        ABS: 'yes',
        EBD: 'yes',
        EBA: 'yes',
        ESS: 'yes',
        DSC: 'yes',
        TCS: 'yes',
        HLA: 'yes',
        ma_hoa_chong_sao_chep_chia_khoa: 'yes',
        canh_bao_chong_trom: 'yes',
        camera_lui: 'yes',
        cam_bien_canh_bao_va_cham_phia_sau: 'yes',
        cam_bien_canh_bao_va_cham_phia_truoc: 'yes',
        camera_quan_sat_360: 'Gói AWD / AWD Package',
        canh_bao_that_day_an_toan: 'no',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        version_id: 5,
        so_tui_khi: 6,
        ABS: 'yes',
        EBD: 'yes',
        EBA: 'yes',
        ESS: 'yes',
        DSC: 'yes',
        TCS: 'yes',
        HLA: 'yes',
        ma_hoa_chong_sao_chep_chia_khoa: 'yes',
        canh_bao_chong_trom: 'yes',
        camera_lui: 'yes',
        cam_bien_canh_bao_va_cham_phia_sau: 'yes',
        cam_bien_canh_bao_va_cham_phia_truoc: 'yes',
        camera_quan_sat_360: 'no',
        canh_bao_that_day_an_toan: 'no',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        version_id: 6,
        so_tui_khi: 6,
        ABS: 'yes',
        EBD: 'yes',
        EBA: 'yes',
        ESS: 'yes',
        DSC: 'yes',
        TCS: 'yes',
        HLA: 'yes',
        ma_hoa_chong_sao_chep_chia_khoa: 'yes',
        canh_bao_chong_trom: 'yes',
        camera_lui: 'yes',
        cam_bien_canh_bao_va_cham_phia_sau: 'yes',
        cam_bien_canh_bao_va_cham_phia_truoc: 'yes',
        camera_quan_sat_360: 'yes',
        canh_bao_that_day_an_toan: 'no',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        version_id: 7,
        so_tui_khi: 6,
        ABS: 'yes',
        EBD: 'yes',
        EBA: 'yes',
        ESS: 'yes',
        DSC: 'yes',
        TCS: 'yes',
        HLA: 'yes',
        ma_hoa_chong_sao_chep_chia_khoa: 'yes',
        canh_bao_chong_trom: 'yes',
        camera_lui: 'yes',
        cam_bien_canh_bao_va_cham_phia_sau: 'yes',
        cam_bien_canh_bao_va_cham_phia_truoc: 'yes',
        camera_quan_sat_360: 'yes',
        canh_bao_that_day_an_toan: 'no',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        version_id: 8,
        so_tui_khi: 6,
        ABS: 'yes',
        EBD: 'yes',
        EBA: 'yes',
        ESS: 'yes',
        DSC: 'yes',
        TCS: 'yes',
        HLA: 'yes',
        ma_hoa_chong_sao_chep_chia_khoa: 'yes',
        canh_bao_chong_trom: 'yes',
        camera_lui: 'yes',
        cam_bien_canh_bao_va_cham_phia_sau: 'yes',
        cam_bien_canh_bao_va_cham_phia_truoc: 'yes',
        camera_quan_sat_360: 'yes',
        canh_bao_that_day_an_toan: 'no',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        version_id: 9,
        so_tui_khi: 6,
        ABS: 'yes',
        EBD: 'yes',
        EBA: 'yes',
        ESS: 'yes',
        DSC: 'yes',
        TCS: 'yes',
        HLA: 'yes',
        ma_hoa_chong_sao_chep_chia_khoa: 'yes',
        canh_bao_chong_trom: 'yes',
        camera_lui: 'yes',
        cam_bien_canh_bao_va_cham_phia_sau: 'yes',
        cam_bien_canh_bao_va_cham_phia_truoc: 'no',
        camera_quan_sat_360: 'no',
        canh_bao_that_day_an_toan: 'yes',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        version_id: 10,
        so_tui_khi: 6,
        ABS: 'yes',
        EBD: 'yes',
        EBA: 'yes',
        ESS: 'yes',
        DSC: 'yes',
        TCS: 'yes',
        HLA: 'yes',
        ma_hoa_chong_sao_chep_chia_khoa: 'yes',
        canh_bao_chong_trom: 'yes',
        camera_lui: 'yes',
        cam_bien_canh_bao_va_cham_phia_sau: 'yes',
        cam_bien_canh_bao_va_cham_phia_truoc: 'no',
        camera_quan_sat_360: 'no',
        canh_bao_that_day_an_toan: 'yes',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        version_id: 11,
        so_tui_khi: 6,
        ABS: 'yes',
        EBD: 'yes',
        EBA: 'yes',
        ESS: 'yes',
        DSC: 'yes',
        TCS: 'yes',
        HLA: 'yes',
        ma_hoa_chong_sao_chep_chia_khoa: 'yes',
        canh_bao_chong_trom: 'yes',
        camera_lui: 'yes',
        cam_bien_canh_bao_va_cham_phia_sau: 'yes',
        cam_bien_canh_bao_va_cham_phia_truoc: 'no',
        camera_quan_sat_360: 'no',
        canh_bao_that_day_an_toan: 'yes',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        version_id: 12,
        so_tui_khi: 7,
        ABS: 'yes',
        EBD: 'yes',
        EBA: 'yes',
        ESS: 'yes',
        DSC: 'yes',
        TCS: 'yes',
        HLA: 'yes',
        ma_hoa_chong_sao_chep_chia_khoa: 'yes',
        canh_bao_chong_trom: 'yes',
        camera_lui: 'yes',
        cam_bien_canh_bao_va_cham_phia_sau: 'yes',
        cam_bien_canh_bao_va_cham_phia_truoc: 'no',
        camera_quan_sat_360: 'no',
        canh_bao_that_day_an_toan: 'no',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        version_id: 13,
        so_tui_khi: 7,
        ABS: 'yes',
        EBD: 'yes',
        EBA: 'yes',
        ESS: 'yes',
        DSC: 'yes',
        TCS: 'yes',
        HLA: 'yes',
        ma_hoa_chong_sao_chep_chia_khoa: 'yes',
        canh_bao_chong_trom: 'yes',
        camera_lui: 'yes',
        cam_bien_canh_bao_va_cham_phia_sau: 'yes',
        cam_bien_canh_bao_va_cham_phia_truoc: 'yes',
        camera_quan_sat_360: 'no',
        canh_bao_that_day_an_toan: 'no',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        version_id: 14,
        so_tui_khi: 2,
        ABS: 'yes',
        EBD: 'yes',
        EBA: 'yes',
        ESS: 'yes',
        DSC: 'yes',
        TCS: 'yes',
        HLA: 'yes',
        ma_hoa_chong_sao_chep_chia_khoa: 'yes',
        canh_bao_chong_trom: 'yes',
        camera_lui: 'no',
        cam_bien_canh_bao_va_cham_phia_sau: 'no',
        cam_bien_canh_bao_va_cham_phia_truoc: 'no',
        camera_quan_sat_360: 'no',
        canh_bao_that_day_an_toan: 'no',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        version_id: 15,
        so_tui_khi: 2,
        ABS: 'yes',
        EBD: 'yes',
        EBA: 'yes',
        ESS: 'yes',
        DSC: 'yes',
        TCS: 'yes',
        HLA: 'yes',
        ma_hoa_chong_sao_chep_chia_khoa: 'yes',
        canh_bao_chong_trom: 'yes',
        camera_lui: 'yes',
        cam_bien_canh_bao_va_cham_phia_sau: 'yes',
        cam_bien_canh_bao_va_cham_phia_truoc: 'no',
        camera_quan_sat_360: 'no',
        canh_bao_that_day_an_toan: 'no',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        version_id: 16,
        so_tui_khi: 2,
        ABS: 'yes',
        EBD: 'yes',
        EBA: 'yes',
        ESS: 'yes',
        DSC: 'yes',
        TCS: 'yes',
        HLA: 'yes',
        ma_hoa_chong_sao_chep_chia_khoa: 'yes',
        canh_bao_chong_trom: 'yes',
        camera_lui: 'yes',
        cam_bien_canh_bao_va_cham_phia_sau: 'yes',
        cam_bien_canh_bao_va_cham_phia_truoc: 'no',
        camera_quan_sat_360: 'no',
        canh_bao_that_day_an_toan: 'no',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        version_id: 17,
        so_tui_khi: 7,
        ABS: 'yes',
        EBD: 'yes',
        EBA: 'yes',
        ESS: 'yes',
        DSC: 'yes',
        TCS: 'yes',
        HLA: 'yes',
        ma_hoa_chong_sao_chep_chia_khoa: 'yes',
        canh_bao_chong_trom: 'yes',
        camera_lui: 'yes',
        cam_bien_canh_bao_va_cham_phia_sau: 'no',
        cam_bien_canh_bao_va_cham_phia_truoc: 'no',
        camera_quan_sat_360: 'no',
        canh_bao_that_day_an_toan: 'no',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        version_id: 18,
        so_tui_khi: 7,
        ABS: 'yes',
        EBD: 'yes',
        EBA: 'yes',
        ESS: 'yes',
        DSC: 'yes',
        TCS: 'yes',
        HLA: 'yes',
        ma_hoa_chong_sao_chep_chia_khoa: 'yes',
        canh_bao_chong_trom: 'yes',
        camera_lui: 'yes',
        cam_bien_canh_bao_va_cham_phia_sau: 'yes',
        cam_bien_canh_bao_va_cham_phia_truoc: 'no',
        camera_quan_sat_360: 'no',
        canh_bao_that_day_an_toan: 'no',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        version_id: 19,
        so_tui_khi: 7,
        ABS: 'yes',
        EBD: 'yes',
        EBA: 'yes',
        ESS: 'yes',
        DSC: 'yes',
        TCS: 'yes',
        HLA: 'yes',
        ma_hoa_chong_sao_chep_chia_khoa: 'yes',
        canh_bao_chong_trom: 'yes',
        camera_lui: 'yes',
        cam_bien_canh_bao_va_cham_phia_sau: 'yes',
        cam_bien_canh_bao_va_cham_phia_truoc: 'yes',
        camera_quan_sat_360: 'no',
        canh_bao_that_day_an_toan: 'no',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        version_id: 20,
        so_tui_khi: 7,
        ABS: 'yes',
        EBD: 'yes',
        EBA: 'yes',
        ESS: 'yes',
        DSC: 'yes',
        TCS: 'yes',
        HLA: 'yes',
        ma_hoa_chong_sao_chep_chia_khoa: 'yes',
        canh_bao_chong_trom: 'yes',
        camera_lui: 'yes',
        cam_bien_canh_bao_va_cham_phia_sau: 'yes',
        cam_bien_canh_bao_va_cham_phia_truoc: 'yes',
        camera_quan_sat_360: 'yes',
        canh_bao_that_day_an_toan: 'no',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        version_id: 21,
        so_tui_khi: 7,
        ABS: 'yes',
        EBD: 'yes',
        EBA: 'yes',
        ESS: 'yes',
        DSC: 'yes',
        TCS: 'yes',
        HLA: 'yes',
        ma_hoa_chong_sao_chep_chia_khoa: 'yes',
        canh_bao_chong_trom: 'yes',
        camera_lui: 'yes',
        cam_bien_canh_bao_va_cham_phia_sau: 'yes',
        cam_bien_canh_bao_va_cham_phia_truoc: 'yes',
        camera_quan_sat_360: 'yes',
        canh_bao_that_day_an_toan: 'no',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        version_id: 22,
        so_tui_khi: 7,
        ABS: 'yes',
        EBD: 'yes',
        EBA: 'yes',
        ESS: 'yes',
        DSC: 'yes',
        TCS: 'yes',
        HLA: 'yes',
        ma_hoa_chong_sao_chep_chia_khoa: 'yes',
        canh_bao_chong_trom: 'yes',
        camera_lui: 'yes',
        cam_bien_canh_bao_va_cham_phia_sau: 'yes',
        cam_bien_canh_bao_va_cham_phia_truoc: 'yes',
        camera_quan_sat_360: 'yes',
        canh_bao_that_day_an_toan: 'no',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        version_id: 23,
        so_tui_khi: 2,
        ABS: 'yes',
        EBD: 'yes',
        EBA: 'yes',
        ESS: 'yes',
        DSC: 'yes',
        TCS: 'yes',
        HLA: 'yes',
        ma_hoa_chong_sao_chep_chia_khoa: 'yes',
        canh_bao_chong_trom: 'yes',
        camera_lui: 'yes',
        cam_bien_canh_bao_va_cham_phia_sau: 'yes',
        cam_bien_canh_bao_va_cham_phia_truoc: 'no',
        camera_quan_sat_360: 'no',
        canh_bao_that_day_an_toan: 'no',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        version_id: 24,
        so_tui_khi: 2,
        ABS: 'yes',
        EBD: 'yes',
        EBA: 'yes',
        ESS: 'yes',
        DSC: 'yes',
        TCS: 'yes',
        HLA: 'yes',
        ma_hoa_chong_sao_chep_chia_khoa: 'yes',
        canh_bao_chong_trom: 'yes',
        camera_lui: 'yes',
        cam_bien_canh_bao_va_cham_phia_sau: 'yes',
        cam_bien_canh_bao_va_cham_phia_truoc: 'no',
        camera_quan_sat_360: 'no',
        canh_bao_that_day_an_toan: 'no',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        version_id: 25,
        so_tui_khi: 7,
        ABS: 'yes',
        EBD: 'yes',
        EBA: 'yes',
        ESS: 'yes',
        DSC: 'yes',
        TCS: 'yes',
        HLA: 'yes',
        ma_hoa_chong_sao_chep_chia_khoa: 'yes',
        canh_bao_chong_trom: 'yes',
        camera_lui: 'yes',
        cam_bien_canh_bao_va_cham_phia_sau: 'yes',
        cam_bien_canh_bao_va_cham_phia_truoc: 'no',
        camera_quan_sat_360: 'no',
        canh_bao_that_day_an_toan: 'no',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        version_id: 26,
        so_tui_khi: 7,
        ABS: 'yes',
        EBD: 'yes',
        EBA: 'yes',
        ESS: 'yes',
        DSC: 'yes',
        TCS: 'yes',
        HLA: 'yes',
        ma_hoa_chong_sao_chep_chia_khoa: 'yes',
        canh_bao_chong_trom: 'yes',
        camera_lui: 'yes',
        cam_bien_canh_bao_va_cham_phia_sau: 'yes',
        cam_bien_canh_bao_va_cham_phia_truoc: 'yes',
        camera_quan_sat_360: 'no',
        canh_bao_that_day_an_toan: 'no',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ], {})
  },

  async down (queryInterface, Sequelize) {
    /**
     * Add commands to revert seed here.
     *
     * Example:
     * await queryInterface.bulkDelete('People', null, {});
     */
    await queryInterface.bulkDelete('safety', null, {});
  }
};
