"use strict";

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    /**
     * Add seed commands here.
     *
     * Example:
     * await queryInterface.bulkInsert('People', [{
     *   name: 'John Doe',
     *   isBetaMember: false
     * }], {});
     */
    await queryInterface.bulkInsert(
      "engines",
      [
        {
          version_id: 1,
          loai_dong_co: "SkyActiv-G 2.0L",
          he_thong_nhien_lieu: "Phun xăng trực tiếp",
          dung_tich_xilanh: "1,998",
          cong_suat_toi_da: "154/6,000",
          momen_xoan_cuc_dai: "200/4,000",
          hop_so: "Tự động 6 cấp / 6 AT",
          che_do_the_thao: "yes",
          GVC: "GVC Plus",
          he_thong_ngung_khoi_dong_thong_minh: "yes",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          version_id: 2,
          loai_dong_co: "SkyActiv-G 2.0L",
          he_thong_nhien_lieu: "Phun xăng trực tiếp",
          dung_tich_xilanh: "1,998",
          cong_suat_toi_da: "154/6,000",
          momen_xoan_cuc_dai: "200/4,000",
          hop_so: "Tự động 6 cấp / 6 AT",
          che_do_the_thao: "yes",
          GVC: "GVC Plus",
          he_thong_ngung_khoi_dong_thong_minh: "yes",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          version_id: 3,
          loai_dong_co: "SkyActiv-G 2.0L",
          he_thong_nhien_lieu: "Phun xăng trực tiếp",
          dung_tich_xilanh: "1,998",
          cong_suat_toi_da: "154/6,000",
          momen_xoan_cuc_dai: "200/4,000",
          hop_so: "Tự động 6 cấp / 6 AT",
          che_do_the_thao: "yes",
          GVC: "GVC Plus",
          he_thong_ngung_khoi_dong_thong_minh: "yes",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          version_id: 4,
          loai_dong_co: "SkyActiv-G 2.0L",
          he_thong_nhien_lieu: "Phun xăng trực tiếp",
          dung_tich_xilanh: "2,488",
          cong_suat_toi_da: "188/6,000",
          momen_xoan_cuc_dai: "252/4,000",
          hop_so: "Tự động 6 cấp / 6 AT",
          che_do_the_thao: "yes",
          GVC: "GVC Plus",
          he_thong_ngung_khoi_dong_thong_minh: "yes",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          version_id: 5,
          loai_dong_co: "Skyactiv-G 2.5L",
          he_thong_nhien_lieu: "Phun xăng trực tiếp",
          dung_tich_xilanh: "2,488",
          cong_suat_toi_da: "188/6,000",
          momen_xoan_cuc_dai: "252/4,000",
          hop_so: "Tự động 6 cấp / 6 AT",
          che_do_the_thao: "yes",
          GVC: "yes",
          he_thong_ngung_khoi_dong_thong_minh: "yes",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          version_id: 6,
          loai_dong_co: "Skyactiv-G 2.5L",
          he_thong_nhien_lieu: "Phun xăng trực tiếp",
          dung_tich_xilanh: "2,488",
          cong_suat_toi_da: "188/6,000",
          momen_xoan_cuc_dai: "252/4,000",
          hop_so: "Tự động 6 cấp / 6 AT",
          che_do_the_thao: "yes",
          GVC: "yes",
          he_thong_ngung_khoi_dong_thong_minh: "i-stop",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          version_id: 7,
          loai_dong_co: "Skyactiv-G 2.5L",
          he_thong_nhien_lieu: "Phun xăng trực tiếp",
          dung_tich_xilanh: "2,488",
          cong_suat_toi_da: "188/6,000",
          momen_xoan_cuc_dai: "252/4,000",
          hop_so: "Tự động 6 cấp / 6 AT",
          che_do_the_thao: "yes",
          GVC: "yes",
          he_thong_ngung_khoi_dong_thong_minh: "yes",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          version_id: 8,
          loai_dong_co: "Skyactiv-G 2.5L",
          he_thong_nhien_lieu: "Phun xăng trực tiếp",
          dung_tich_xilanh: "2,488",
          cong_suat_toi_da: "188/6,000",
          momen_xoan_cuc_dai: "252/4,000",
          hop_so: "Tự động 6 cấp / 6 AT",
          che_do_the_thao: "yes",
          GVC: "yes",
          he_thong_ngung_khoi_dong_thong_minh: "i-stop",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          version_id: 9,
          loai_dong_co: "SkyActiv-G 1.5",
          he_thong_nhien_lieu: "Phun xăng trực tiếp / Direct injection",
          dung_tich_xilanh: "1,496",
          cong_suat_toi_da: "110/6,000",
          momen_xoan_cuc_dai: "144/4,000",
          hop_so: "Tự động 6 cấp + Chế độ thể thao",
          che_do_the_thao: "yes",
          GVC: "GVC",
          he_thong_ngung_khoi_dong_thong_minh: "yes",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          version_id: 10,
          loai_dong_co: "SkyActiv-G 1.5",
          he_thong_nhien_lieu: "Phun xăng trực tiếp / Direct injection",
          dung_tich_xilanh: "1,496",
          cong_suat_toi_da: "110/6,000",
          momen_xoan_cuc_dai: "144/4,000",
          hop_so: "Tự động 6 cấp + Chế độ thể thao",
          che_do_the_thao: "yes",
          GVC: "GVC",
          he_thong_ngung_khoi_dong_thong_minh: "yes",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          version_id: 11,
          loai_dong_co: "SkyActiv-G 1.5",
          he_thong_nhien_lieu: "Phun xăng trực tiếp / Direct injection",
          dung_tich_xilanh: "1,496",
          cong_suat_toi_da: "110/6,000",
          momen_xoan_cuc_dai: "144/4,000",
          hop_so: "Tự động 6 cấp + Chế độ thể thao",
          che_do_the_thao: "yes",
          GVC: "GVC",
          he_thong_ngung_khoi_dong_thong_minh: "yes",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          version_id: 12,
          loai_dong_co: "SkyActiv-G 2.0",
          he_thong_nhien_lieu: "Phun xăng trực tiếp / Direct injection",
          dung_tich_xilanh: "1,998",
          cong_suat_toi_da: "153/6,000",
          momen_xoan_cuc_dai: "200/4,000",
          hop_so: "6AT + Chế độ lái thể thao",
          che_do_the_thao: "yes",
          GVC: "GVC Plus",
          he_thong_ngung_khoi_dong_thong_minh: "yes",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          version_id: 13,
          loai_dong_co: "SkyActiv-G 2.0",
          he_thong_nhien_lieu: "Phun xăng trực tiếp / Direct injection",
          dung_tich_xilanh: "1,998",
          cong_suat_toi_da: "153/6,000",
          momen_xoan_cuc_dai: "200/4,000",
          hop_so: "6AT + Chế độ lái thể thao",
          che_do_the_thao: "yes",
          GVC: "GVC Plus",
          he_thong_ngung_khoi_dong_thong_minh: "yes",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          version_id: 14,
          loai_dong_co: "Skyactiv-G 1.5L",
          he_thong_nhien_lieu: "Phun xăng trực tiếp / Direct injection",
          dung_tich_xilanh: "1,496",
          cong_suat_toi_da: "109/6000",
          momen_xoan_cuc_dai: "141/4000",
          hop_so: "6AT",
          che_do_the_thao: "yes",
          GVC: "yes",
          he_thong_ngung_khoi_dong_thong_minh: "no",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          version_id: 15,
          loai_dong_co: "Skyactiv-G 1.5L",
          he_thong_nhien_lieu: "Phun xăng trực tiếp / Direct injection",
          dung_tich_xilanh: "1,496",
          cong_suat_toi_da: "109/6000",
          momen_xoan_cuc_dai: "141/4000",
          hop_so: "6AT",
          che_do_the_thao: "yes",
          GVC: "yes",
          he_thong_ngung_khoi_dong_thong_minh: "yes",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          version_id: 16,
          loai_dong_co: "Skyactiv-G 1.5L",
          he_thong_nhien_lieu: "Phun xăng trực tiếp / Direct injection",
          dung_tich_xilanh: "1,496",
          cong_suat_toi_da: "109/6000",
          momen_xoan_cuc_dai: "141/4000",
          hop_so: "6AT",
          che_do_the_thao: "yes",
          GVC: "yes",
          he_thong_ngung_khoi_dong_thong_minh: "yes",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          version_id: 17,
          loai_dong_co: "Skyactiv-G 1.5L",
          he_thong_nhien_lieu: "Phun xăng trực tiếp / Direct injection",
          dung_tich_xilanh: "1,496",
          cong_suat_toi_da: "110/6000",
          momen_xoan_cuc_dai: "146/3500",
          hop_so: "6AT",
          che_do_the_thao: "yes",
          GVC: "yes",
          he_thong_ngung_khoi_dong_thong_minh: "no",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          version_id: 18,
          loai_dong_co: "Skyactiv-G 1.5L",
          he_thong_nhien_lieu: "Phun xăng trực tiếp / Direct injection",
          dung_tich_xilanh: "1,496",
          cong_suat_toi_da: "110/6000",
          momen_xoan_cuc_dai: "146/3500",
          hop_so: "6AT",
          che_do_the_thao: "yes",
          GVC: "yes",
          he_thong_ngung_khoi_dong_thong_minh: "no",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          version_id: 19,
          loai_dong_co: "Skyactiv-G 1.5L",
          he_thong_nhien_lieu: "Phun xăng trực tiếp / Direct injection",
          dung_tich_xilanh: "1,496",
          cong_suat_toi_da: "110/6000",
          momen_xoan_cuc_dai: "146/3500",
          hop_so: "6AT",
          che_do_the_thao: "yes",
          GVC: "yes",
          he_thong_ngung_khoi_dong_thong_minh: "no",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          version_id: 20,
          loai_dong_co: "SkyActiv-G 2.0L",
          he_thong_nhien_lieu: "Phun xăng trực tiếp",
          dung_tich_xilanh: "1998",
          cong_suat_toi_da: "154/6000",
          momen_xoan_cuc_dai: "200/4000",
          hop_so: "Tự động 6 cấp / 6AT",
          che_do_the_thao: "yes",
          GVC: "yes",
          he_thong_ngung_khoi_dong_thong_minh: "yes",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          version_id: 21,
          loai_dong_co: "SkyActiv-G 2.0L",
          he_thong_nhien_lieu: "Phun xăng trực tiếp",
          dung_tich_xilanh: "1998",
          cong_suat_toi_da: "154/6000",
          momen_xoan_cuc_dai: "252/4000",
          hop_so: "Tự động 6 cấp / 6AT",
          che_do_the_thao: "yes",
          GVC: "yes",
          he_thong_ngung_khoi_dong_thong_minh: "yes",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          version_id: 22,
          loai_dong_co: "SkyActiv-G 2.0L",
          he_thong_nhien_lieu: "Phun xăng trực tiếp",
          dung_tich_xilanh: "2488",
          cong_suat_toi_da: "188/6000",
          momen_xoan_cuc_dai: "252/4000",
          hop_so: "Tự động 6 cấp / 6AT",
          che_do_the_thao: "yes",
          GVC: "yes",
          he_thong_ngung_khoi_dong_thong_minh: "yes",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          version_id: 23,
          loai_dong_co: "Skyactiv-G 1.5L",
          he_thong_nhien_lieu: "Phun xăng trực tiếp / Direct injection",
          dung_tich_xilanh: "1496",
          cong_suat_toi_da: "109/6000",
          momen_xoan_cuc_dai: "141/4000",
          hop_so: "6AT",
          che_do_the_thao: "yes",
          GVC: "yes",
          he_thong_ngung_khoi_dong_thong_minh: "yes",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          version_id: 24,
          loai_dong_co: "Skyactiv-G 1.5L",
          he_thong_nhien_lieu: "Phun xăng trực tiếp / Direct injection",
          dung_tich_xilanh: "1496",
          cong_suat_toi_da: "109/6000",
          momen_xoan_cuc_dai: "141/4000",
          hop_so: "6AT",
          che_do_the_thao: "yes",
          GVC: "yes",
          he_thong_ngung_khoi_dong_thong_minh: "yes",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          version_id: 25,
          loai_dong_co: "Skyactiv-G 1.5L",
          he_thong_nhien_lieu: "Phun xăng trực tiếp / Direct injection",
          dung_tich_xilanh: "1496",
          cong_suat_toi_da: "110/6000",
          momen_xoan_cuc_dai: "146/3500",
          hop_so: "6AT",
          che_do_the_thao: "yes",
          GVC: "GVC Plus",
          he_thong_ngung_khoi_dong_thong_minh: "yes",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          version_id: 26,
          loai_dong_co: "Skyactiv-G 1.5L",
          he_thong_nhien_lieu: "Phun xăng trực tiếp / Direct injection",
          dung_tich_xilanh: "1496",
          cong_suat_toi_da: "110/6000",
          momen_xoan_cuc_dai: "146/3500",
          hop_so: "6AT",
          che_do_the_thao: "yes",
          GVC: "GVC Plus",
          he_thong_ngung_khoi_dong_thong_minh: "yes",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          version_id: 27,
          loai_dong_co: "Skyactiv-G 1.5L",
          he_thong_nhien_lieu: "Phun xăng trực tiếp / Direct injection",
          dung_tich_xilanh: "1496",
          cong_suat_toi_da: "110/6000",
          momen_xoan_cuc_dai: "146/3500",
          hop_so: "6AT",
          che_do_the_thao: "yes",
          GVC: "GVC Plus",
          he_thong_ngung_khoi_dong_thong_minh: "yes",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      {}
    );
  },

  async down(queryInterface, Sequelize) {
    /**
     * Add commands to revert seed here.
     *
     * Example:
     * await queryInterface.bulkDelete('People', null, {});
     */
    await queryInterface.bulkDelete("engines", null, {});
  },
};
