"use strict";

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    /**
     * Add seed commands here.
     *
     * Example:
     * await queryInterface.bulkInsert('People', [{
     *   name: 'John Doe',
     *   isBetaMember: false
     * }], {});
     */
    await queryInterface.bulkInsert(
      "sizes",
      [
        {
          version_id: 1,
          kich_thuoc_tong_the: "4,550 x 1,840 x 1,680",
          chieu_dai_co_so: "2,700",
          ban_kinh_quay_vong_toi_thieu: "5.46",
          khoang_sang_gam_xe: "200",
          khoi_luong_khong_tai: "1,550",
          khoi_luong_toan_tai: "2,000",
          the_tich_khoang_hanh_ly: "442",
          dung_tich_thung_nhien_lieu: "56",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          version_id: 2,
          kich_thuoc_tong_the: "4,550 x 1,840 x 1,680",
          chieu_dai_co_so: "2,700",
          ban_kinh_quay_vong_toi_thieu: "5.46",
          khoang_sang_gam_xe: "200",
          khoi_luong_khong_tai: "1,550",
          khoi_luong_toan_tai: "2,000",
          the_tich_khoang_hanh_ly: "442",
          dung_tich_thung_nhien_lieu: "56",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          version_id: 3,
          kich_thuoc_tong_the: "4,550 x 1,840 x 1,680",
          chieu_dai_co_so: "2,700",
          ban_kinh_quay_vong_toi_thieu: "5.46",
          khoang_sang_gam_xe: "200",
          khoi_luong_khong_tai: "1,550",
          khoi_luong_toan_tai: "2,000",
          the_tich_khoang_hanh_ly: "442",
          dung_tich_thung_nhien_lieu: "56",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          version_id: 4,
          kich_thuoc_tong_the: "4,550 x 1,840 x 1,680",
          chieu_dai_co_so: "2,700",
          ban_kinh_quay_vong_toi_thieu: "5.46",
          khoang_sang_gam_xe: "200",
          khoi_luong_khong_tai: "1,630",
          khoi_luong_toan_tai: "2,080",
          the_tich_khoang_hanh_ly: "442",
          dung_tich_thung_nhien_lieu: "56",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          version_id: 5,
          kich_thuoc_tong_the: "4900 x 1840 x 1730",
          chieu_dai_co_so: "2930",
          ban_kinh_quay_vong_toi_thieu: "5.8",
          khoang_sang_gam_xe: "200",
          khoi_luong_khong_tai: "1770",
          khoi_luong_toan_tai: "2365",
          the_tich_khoang_hanh_ly: "209 - 742",
          dung_tich_thung_nhien_lieu: "72",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          version_id: 6,
          kich_thuoc_tong_the: "4900 x 1840 x 1730",
          chieu_dai_co_so: "2930",
          ban_kinh_quay_vong_toi_thieu: "5.8",
          khoang_sang_gam_xe: "200",
          khoi_luong_khong_tai: "1770",
          khoi_luong_toan_tai: "2365",
          the_tich_khoang_hanh_ly: "209 - 742",
          dung_tich_thung_nhien_lieu: "72",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          version_id: 7,
          kich_thuoc_tong_the: "4900 x 1840 x 1730",
          chieu_dai_co_so: "2930",
          ban_kinh_quay_vong_toi_thieu: "5.8",
          khoang_sang_gam_xe: "185",
          khoi_luong_khong_tai: "1850",
          khoi_luong_toan_tai: "2445",
          the_tich_khoang_hanh_ly: "209 - 742",
          dung_tich_thung_nhien_lieu: "74",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          version_id: 8,
          kich_thuoc_tong_the: "4900 x 1840 x 1730",
          chieu_dai_co_so: "2930",
          ban_kinh_quay_vong_toi_thieu: "5.8",
          khoang_sang_gam_xe: "185",
          khoi_luong_khong_tai: "1850",
          khoi_luong_toan_tai: "2445",
          the_tich_khoang_hanh_ly: "209 - 742",
          dung_tich_thung_nhien_lieu: "74",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          version_id: 9,
          kich_thuoc_tong_the: "4,275 x 1,765 x 1,535",
          chieu_dai_co_so: "2,570",
          ban_kinh_quay_vong_toi_thieu: "5.3",
          khoang_sang_gam_xe: "155",
          khoi_luong_khong_tai: "1,256",
          khoi_luong_toan_tai: "1,695",
          the_tich_khoang_hanh_ly: "350 - 1,260",
          dung_tich_thung_nhien_lieu: "48",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          version_id: 10,
          kich_thuoc_tong_the: "4,275 x 1,765 x 1,535",
          chieu_dai_co_so: "2,570",
          ban_kinh_quay_vong_toi_thieu: "5.3",
          khoang_sang_gam_xe: "155",
          khoi_luong_khong_tai: "1,256",
          khoi_luong_toan_tai: "1,695",
          the_tich_khoang_hanh_ly: "350 - 1,260",
          dung_tich_thung_nhien_lieu: "48",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          version_id: 11,
          kich_thuoc_tong_the: "4,275 x 1,765 x 1,535",
          chieu_dai_co_so: "2,570",
          ban_kinh_quay_vong_toi_thieu: "5.3",
          khoang_sang_gam_xe: "155",
          khoi_luong_khong_tai: "1,256",
          khoi_luong_toan_tai: "1,695",
          the_tich_khoang_hanh_ly: "350 - 1,260",
          dung_tich_thung_nhien_lieu: "48",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          version_id: 12,
          kich_thuoc_tong_the: "4,395 x 1,795 x 1,540",
          chieu_dai_co_so: "2,655",
          ban_kinh_quay_vong_toi_thieu: "5.3",
          khoang_sang_gam_xe: "175",
          khoi_luong_khong_tai: "1,441",
          khoi_luong_toan_tai: "1,936",
          the_tich_khoang_hanh_ly: "430 - 1,460",
          dung_tich_thung_nhien_lieu: "51",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          version_id: 13,
          kich_thuoc_tong_the: "4,395 x 1,795 x 1,540",
          chieu_dai_co_so: "2,655",
          ban_kinh_quay_vong_toi_thieu: "5.3",
          khoang_sang_gam_xe: "175",
          khoi_luong_khong_tai: "1,452",
          khoi_luong_toan_tai: "1,936",
          the_tich_khoang_hanh_ly: "430 - 1,406",
          dung_tich_thung_nhien_lieu: "51",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          version_id: 14,
          kich_thuoc_tong_the: "4340 x 1695 x 1470",
          chieu_dai_co_so: "2570",
          ban_kinh_quay_vong_toi_thieu: "4.7",
          khoang_sang_gam_xe: "140",
          khoi_luong_khong_tai: "1074",
          khoi_luong_toan_tai: "1538",
          the_tich_khoang_hanh_ly: "440",
          dung_tich_thung_nhien_lieu: "51",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          version_id: 15,
          kich_thuoc_tong_the: "4340 x 1695 x 1470",
          chieu_dai_co_so: "2570",
          ban_kinh_quay_vong_toi_thieu: "4.7",
          khoang_sang_gam_xe: "140",
          khoi_luong_khong_tai: "1111",
          khoi_luong_toan_tai: "1538",
          the_tich_khoang_hanh_ly: "440",
          dung_tich_thung_nhien_lieu: "51",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          version_id: 16,
          kich_thuoc_tong_the: "4340 x 1695 x 1470",
          chieu_dai_co_so: "2570",
          ban_kinh_quay_vong_toi_thieu: "4.7",
          khoang_sang_gam_xe: "140",
          khoi_luong_khong_tai: "1111",
          khoi_luong_toan_tai: "1538",
          the_tich_khoang_hanh_ly: "440",
          dung_tich_thung_nhien_lieu: "51",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          version_id: 17,
          kich_thuoc_tong_the: "4660 x 1795 x 1440",
          chieu_dai_co_so: "2725",
          ban_kinh_quay_vong_toi_thieu: "5.3",
          khoang_sang_gam_xe: "145",
          khoi_luong_khong_tai: "1330",
          khoi_luong_toan_tai: "1780",
          the_tich_khoang_hanh_ly: "450",
          dung_tich_thung_nhien_lieu: "51",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          version_id: 18,
          kich_thuoc_tong_the: "4660 x 1795 x 1440",
          chieu_dai_co_so: "2725",
          ban_kinh_quay_vong_toi_thieu: "5.3",
          khoang_sang_gam_xe: "145",
          khoi_luong_khong_tai: "1330",
          khoi_luong_toan_tai: "1780",
          the_tich_khoang_hanh_ly: "450",
          dung_tich_thung_nhien_lieu: "51",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          version_id: 19,
          kich_thuoc_tong_the: "4660 x 1795 x 1440",
          chieu_dai_co_so: "2725",
          ban_kinh_quay_vong_toi_thieu: "5.3",
          khoang_sang_gam_xe: "145",
          khoi_luong_khong_tai: "1330",
          khoi_luong_toan_tai: "1780",
          the_tich_khoang_hanh_ly: "450",
          dung_tich_thung_nhien_lieu: "51",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          version_id: 20,
          kich_thuoc_tong_the: "4865 x 1840 x 1450",
          chieu_dai_co_so: "2830",
          ban_kinh_quay_vong_toi_thieu: "5.6",
          khoang_sang_gam_xe: "165",
          khoi_luong_khong_tai: "1520",
          khoi_luong_toan_tai: "1970",
          the_tich_khoang_hanh_ly: "480",
          dung_tich_thung_nhien_lieu: "62",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          version_id: 21,
          kich_thuoc_tong_the: "4865 x 1840 x 1450",
          chieu_dai_co_so: "2830",
          ban_kinh_quay_vong_toi_thieu: "5.6",
          khoang_sang_gam_xe: "165",
          khoi_luong_khong_tai: "1520",
          khoi_luong_toan_tai: "1970",
          the_tich_khoang_hanh_ly: "480",
          dung_tich_thung_nhien_lieu: "62",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          version_id: 22,
          kich_thuoc_tong_the: "4865 x 1840 x 1450",
          chieu_dai_co_so: "2830",
          ban_kinh_quay_vong_toi_thieu: "5.6",
          khoang_sang_gam_xe: "165",
          khoi_luong_khong_tai: "1550",
          khoi_luong_toan_tai: "2000",
          the_tich_khoang_hanh_ly: "480",
          dung_tich_thung_nhien_lieu: "62",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          version_id: 23,
          kich_thuoc_tong_the: "4065 x 1695 x 1515",
          chieu_dai_co_so: "2570",
          ban_kinh_quay_vong_toi_thieu: "4.7",
          khoang_sang_gam_xe: "145",
          khoi_luong_khong_tai: "1092",
          khoi_luong_toan_tai: "1524",
          the_tich_khoang_hanh_ly: "280",
          dung_tich_thung_nhien_lieu: "44",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          version_id: 24,
          kich_thuoc_tong_the: "4065 x 1695 x 1515",
          chieu_dai_co_so: "2570",
          ban_kinh_quay_vong_toi_thieu: "4.7",
          khoang_sang_gam_xe: "145",
          khoi_luong_khong_tai: "1092",
          khoi_luong_toan_tai: "1524",
          the_tich_khoang_hanh_ly: "280",
          dung_tich_thung_nhien_lieu: "44",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          version_id: 25,
          kich_thuoc_tong_the: "4460 x 1795 x 1435",
          chieu_dai_co_so: "2725",
          ban_kinh_quay_vong_toi_thieu: "5.3",
          khoang_sang_gam_xe: "145",
          khoi_luong_khong_tai: "1340",
          khoi_luong_toan_tai: "1790",
          the_tich_khoang_hanh_ly: "334",
          dung_tich_thung_nhien_lieu: "51",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          version_id: 26,
          kich_thuoc_tong_the: "4460 x 1795 x 1435",
          chieu_dai_co_so: "2725",
          ban_kinh_quay_vong_toi_thieu: "5.3",
          khoang_sang_gam_xe: "145",
          khoi_luong_khong_tai: "1340",
          khoi_luong_toan_tai: "1790",
          the_tich_khoang_hanh_ly: "334",
          dung_tich_thung_nhien_lieu: "51",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          version_id: 27,
          kich_thuoc_tong_the: "4460 x 1795 x 1435",
          chieu_dai_co_so: "2725",
          ban_kinh_quay_vong_toi_thieu: "5.3",
          khoang_sang_gam_xe: "145",
          khoi_luong_khong_tai: "1340",
          khoi_luong_toan_tai: "1790",
          the_tich_khoang_hanh_ly: "334",
          dung_tich_thung_nhien_lieu: "51",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      {}
    );
  },

  async down(queryInterface, Sequelize) {
    /**
     * Add commands to revert seed here.
     *
     * Example:
     * await queryInterface.bulkDelete('People', null, {});
     */
    await queryInterface.bulkDelete("sizes", null, {});
  },
};
